### ISSUE TITLE
您好，可以再次提供一下训练LPNet的数据集吗？

### ISSUE THREAD

**Issue by gocse** [harrytea/UDoc-GAN#8]
原百度网盘分享的链接已经失效了，想了解训练集数据结构是怎么样的，谢谢

**Comment by harrytea** [comment]
抱歉刚刚看到，已经在代码中更新~

**Comment by gocse** [comment]
> 抱歉刚刚看到，已经在代码中更新~

非常感谢作者百忙之中更新链接。可能我看到的时候太迟了，新的链接还是无法查看，如果作者方便的话可以使用其他网盘或者发邮箱吗，非常感谢，我的邮箱是chenxkj@gmail.com

**Comment by harrytea** [comment]
> > 抱歉刚刚看到，已经在代码中更新~
> 
> 非常感谢作者百忙之中更新链接。可能我看到的时候太迟了，新的链接还是无法查看，如果作者方便的话可以使用其他网盘或者发邮箱吗，非常感谢，我的邮箱是[chenxkj@gmail.com](mailto:chenxkj@gmail.com)

不知道为啥被百度网盘识别为不安全信息了，我下载下来发你邮箱哈

**Comment by harrytea** [comment]
> > 抱歉刚刚看到，已经在代码中更新~
> 
> 非常感谢作者百忙之中更新链接。可能我看到的时候太迟了，新的链接还是无法查看，如果作者方便的话可以使用其他网盘或者发邮箱吗，非常感谢，我的邮箱是[chenxkj@gmail.com](mailto:chenxkj@gmail.com)

他显示我下载的内容包含违规信息。。。不让我下载。。我看看怎么申诉一下

**Comment by gocse** [comment]
> > > 抱歉刚刚看到，已经在代码中更新~
> > 
> > 
> > 非常感谢作者百忙之中更新链接。可能我看到的时候太迟了，新的链接还是无法查看，如果作者方便的话可以使用其他网盘或者发邮箱吗，非常感谢，我的邮箱是[chenxkj@gmail.com](mailto:chenxkj@gmail.com)
> 
> 他显示我下载的内容包含违规信息。。。不让我下载。。我看看怎么申诉一下

辛苦作者了，现在申诉请求怎么样了

**Comment by harrytea** [comment]
> > > > 抱歉刚刚看到，已经在代码中更新~
> > > 
> > > 
> > > 非常感谢作者百忙之中更新链接。可能我看到的时候太迟了，新的链接还是无法查看，如果作者方便的话可以使用其他网盘或者发邮箱吗，非常感谢，我的邮箱是[chenxkj@gmail.com](mailto:chenxkj@gmail.com)
> > 
> > 
> > 他显示我下载的内容包含违规信息。。。不让我下载。。我看看怎么申诉一下
> 
> 辛苦作者了，现在申诉请求怎么样了

还没回复，我在申诉一下

**Comment by harrytea** [comment]
> > > > 抱歉刚刚看到，已经在代码中更新~
> > > 
> > > 
> > > 非常感谢作者百忙之中更新链接。可能我看到的时候太迟了，新的链接还是无法查看，如果作者方便的话可以使用其他网盘或者发邮箱吗，非常感谢，我的邮箱是[chenxkj@gmail.com](mailto:chenxkj@gmail.com)
> > 
> > 
> > 他显示我下载的内容包含违规信息。。。不让我下载。。我看看怎么申诉一下
> 
> 辛苦作者了，现在申诉请求怎么样了

我知道为啥了，我直接用网盘解压了一下，其中有一幅图好像违规了，其他图应该可以下载，等解压完我发给你

**Comment by harrytea** [comment]
> > > > 抱歉刚刚看到，已经在代码中更新~
> > > 
> > > 
> > > 非常感谢作者百忙之中更新链接。可能我看到的时候太迟了，新的链接还是无法查看，如果作者方便的话可以使用其他网盘或者发邮箱吗，非常感谢，我的邮箱是[chenxkj@gmail.com](mailto:chenxkj@gmail.com)
> > 
> > 
> > 他显示我下载的内容包含违规信息。。。不让我下载。。我看看怎么申诉一下
> 
> 辛苦作者了，现在申诉请求怎么样了

已更新
